module.exports.jobsData = {
    "jobs": [
        {
            "id": 1764732,
            "url": "https://remotive.com/remote-jobs/data/data-analyst-1764732",
            "title": "Data Analyst",
            "company_name": "Current Health",
            "company_logo": "https://remotive.com/job/1764732/logo",
            "category": "Data",
            "tags": [
                "AWS",
                "business intelligence",
                "cloud",
                "data science",
                "python",
                "sql",
                "agile",
                "project management",
                "jira",
                "healthcare",
                "data analysis",
                "hardware",
                "tableau",
                "business analysis",
                "engineering management",
                "travel",
                "insurance"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T05:41:39",
            "candidate_required_location": "USA",
            "salary": ""
        },
        {
            "id": 1760242,
            "url": "https://remotive.com/remote-jobs/business/ticket-pricing-analyst-1760242",
            "title": "Ticket Pricing Analyst",
            "company_name": "Quantum Sports + Entertainment",
            "company_logo": "https://remotive.com/job/1760242/logo",
            "category": "Business",
            "tags": [
                "business intelligence",
                "research",
                "market research",
                "ticketing"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T05:41:34",
            "candidate_required_location": "USA",
            "salary": ""
        },
        {
            "id": 1765702,
            "url": "https://remotive.com/remote-jobs/software-dev/mobile-developer-1765702",
            "title": "Mobile Developer",
            "company_name": "Cross Border Talents",
            "company_logo": "https://remotive.com/job/1765702/logo",
            "category": "Software Development",
            "tags": [
                "android",
                "ios",
                "javascript",
                "php",
                "MySQL"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T05:39:52",
            "candidate_required_location": "Portugal",
            "salary": "",
        },
        {
            "id": 1766027,
            "url": "https://remotive.com/remote-jobs/sales/account-executive-1766027",
            "title": "Account Executive",
            "company_name": "Quantum Metric",
            "company_logo": "https://remotive.com/job/1766027/logo",
            "category": "Sales",
            "tags": [
                "android",
                "ecommerce",
                "ios",
                "saas",
                "salesforce",
                "product marketing",
                "CX",
                "research",
                "product management",
                "analytics",
                "retail",
                "enterprise sales",
                "partnerships",
                "onboarding",
                "startup",
                "financial services",
                "software sales",
                "sales leadership",
                "travel"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:43",
            "candidate_required_location": "UK",
            "salary": ""
        },
        {
            "id": 1763375,
            "url": "https://remotive.com/remote-jobs/design/senior-brand-designer-1763375",
            "title": "Senior Brand Designer",
            "company_name": "Secureframe",
            "company_logo": "https://remotive.com/job/1763375/logo",
            "category": "Design",
            "tags": [
                "saas",
                "security",
                "social media",
                "AI/ML",
                "project management",
                "advertising",
                "graphic design",
                "asana",
                "demand generation",
                "marketplace",
                "travel"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:31",
            "candidate_required_location": "Northern America",
            "salary": ""
        },
        {
            "id": 1761517,
            "url": "https://remotive.com/remote-jobs/design/level-designer-1761517",
            "title": "Level Designer",
            "company_name": "Worlds",
            "company_logo": "https://remotive.com/job/1761517/logo",
            "category": "Design",
            "tags": [
                "swift",
                "editing",
                "prototyping",
                "iterative design",
                "testing",
                "banking"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:31",
            "candidate_required_location": "Worldwide",
            "salary": ""
        },
        {
            "id": 1764457,
            "url": "https://remotive.com/remote-jobs/design/senior-project-manager-social-creative-1764457",
            "title": "Senior Project Manager (Social / Creative)",
            "company_name": "Praytell",
            "company_logo": "https://remotive.com/job/1764457/logo",
            "category": "Design",
            "tags": [
                "go",
                "project management",
                "diversity",
                "insurance",
                "mental health"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:29",
            "candidate_required_location": "USA",
            "salary": ""
        },
        {
            "id": 1760369,
            "url": "https://remotive.com/remote-jobs/customer-support/manager-community-navigator-program-1760369",
            "title": "Manager, Community Navigator Program",
            "company_name": "Hispanic Access Foundation",
            "company_logo": "https://remotive.com/job/1760369/logo",
            "category": "Customer Service",
            "tags": [
                "project management",
                "program manager",
                "nonprofit",
                "travel"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:19",
            "candidate_required_location": "USA",
            "salary": ""
        },
        {
            "id": 1761328,
            "url": "https://remotive.com/remote-jobs/customer-support/client-success-manager-1761328",
            "title": "Client Success Manager",
            "company_name": "Propelus",
            "company_logo": "https://remotive.com/job/1761328/logo",
            "category": "Customer Service",
            "tags": [
                "swift",
                "CRM",
                "technical support",
                "diversity",
                "travel",
                "REST",
                "insurance"
            ],
            "job_type": "",
            "publication_date": "2023-08-26T03:39:19",
            "candidate_required_location": "USA",
            "salary": ""
        },
        {
            "id": 1766292,
            "url": "https://remotive.com/remote-jobs/software-dev/web-developer-1766292",
            "title": "Web Developer",
            "company_name": "Xpanxion",
            "company_logo": "https://remotive.com/job/1766292/logo",
            "category": "Software Development",
            "tags": [
                "api",
                "CSS",
                "git",
                "html",
                "javascript",
                "react",
                "vue.js",
                "agile",
                "web applications",
                "angular ",
                "SOLID",
                "computer science",
                "REST"
            ],
            "job_type": "full_time",
            "publication_date": "2023-08-26T03:39:11",
            "candidate_required_location": "USA",
            "salary": ""
        }
    ]
}